{% set name = "nd2" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f9908301586d68cd304d4e144107d462042c43ea02a811ed87f07664e750dbb1

build:
  number: 1
  skip: true  # [win or py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
    - libgomp  # [linux]
  host:
    - python
    - pip
    - cython
    - numpy
    - libtiff
    - libzlib
    - jpeg
    - setuptools_scm
  run:
    - python
    - lxml
    - resource_backed_dask_array
    - {{ pin_compatible('numpy') }}
    - typing_extensions
    - imagecodecs
    - wurlitzer  # [not win]

test:
  imports:
    - nd2
    - nd2._sdk.latest
    - nd2._legacy
    - imagecodecs._jpeg2k
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tlambert03/nd2
  license: BSD-3-Clause AND LicenseRef-LIMnd2sdk
  license_file:
    - LICENSE
    - src/sdk/LICENSE
  summary: nd2 (Nikon NIS Elements) file reader for python

extra:
  recipe-maintainers:
    - tlambert03
