{% set name = "nd2" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 379640d8c6c9b3401f231931d64afee790b2a8d896754c3c1c354544bf250781

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.7
    - resource_backed_dask_array
    - typing-extensions
    - numpy
    - imagecodecs

test:
  imports:
    - nd2
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tlambert03/nd2
  license: BSD-3-Clause
  license_file: LICENSE
  summary: nd2 (Nikon NIS Elements) file reader for python

extra:
  recipe-maintainers:
    - tlambert03
